spring.application.name=food-delivery-app

spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery
spring.datasource.username=fd_user
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

JWT_SECRET=Qm1pQzZqQ1FhV3p1V0t3a1V1T3ZtZ0p2b1N0eU9nZ1JqT1p6Y0t0cQ==

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.show-sql=true

spring.flyway.enabled=true
logging.level.org.springframework.core.env=DEBUG
#docker run --name postgres-db -e POSTGRES_DB=food_delivery -e POSTGRES_USER=fd_user -e POSTGRES_PASSWORD=secret123 -p 5432:5432 -d postgres:18.3-alpine

# ? Skip version check
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.jpa.hibernate.ddl-auto=create-drop