spring.application.name=food-delivery-app

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5433/Food_Delivery

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=1234

# JDBC driver (optional in newer Spring Boot versions)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate behavior
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialect (usually auto-detected, but you can set it manually)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect